### ISSUE TITLE
[Test Coverage] Cover exception in SalesGraphQl\Model\Resolver\Orders

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#1009]
### Description:

Cover with API-functional tests:
https://github.com/magento/graphql-ce/blob/746038efe9fd49d0eb2c1f0349100d80f9ac4d10/app/code/Magento/SalesGraphQl/Model/Resolver/Orders.php#L48

### TestCases:
```
 - testQueryOrdersAsGuest
```

### Examples:
[Magento\GraphQl\Customer](https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer)
[Magento\GraphQl\Quote\Customer](https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer)

### Guide:
[Graphql Functional Testing](https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html)

**Comment by atwixfirster** [comment]
Pull request: https://github.com/magento/graphql-ce/pull/1028

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#1028 by @atwixfirster in 2.3-develop branch
Related commit(s):
 - [7b345f0be1e059aa48227e945b81de8ac0c6ced8](https://github.com/magento/graphql-ce/commit/7b345f0be1e059aa48227e945b81de8ac0c6ced8)

The fix will be available with the upcoming 2.3.4 release.
