### ISSUE TITLE
[Test Coverage] Extend coverage for CustomerGraphQL

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#1011]
### Description:

Cover with API-functional tests:
https://github.com/magento/graphql-ce/blob/f52ba88cf0ba26ae8b30eb6257a80dd2afb9958c/app/code/Magento/CustomerGraphQl/Model/Customer/ExtractCustomerData.php#L82
https://github.com/magento/graphql-ce/blob/3e03eec3c0e831c9536be75248b5c5503f481514/app/code/Magento/CustomerGraphQl/Model/Customer/Address/ExtractCustomerAddressData.php#L98
https://github.com/magento/graphql-ce/blob/da8d6ac580f3b3e47f913b7f0618e330a8693fc8/app/code/Magento/CustomerGraphQl/Model/Customer/GetAllowedCustomerAttributes.php#L84

### TestCases:
```
```

### Examples:
[Magento\GraphQl\Customer](https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Customer)
[Magento\GraphQl\Quote\Customer](https://github.com/magento/graphql-ce/tree/2.3-develop/dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Customer)

### Guide:
[Graphql Functional Testing](https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html)

**Comment by magento-engcom-team** [comment]
Hi @TomashKhamlai. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#1030 by @TomashKhamlai in 2.3-develop branch
Related commit(s):
 - [56382f1a603bf39dbe51098971ebbae1bb4292f1](https://github.com/magento/graphql-ce/commit/56382f1a603bf39dbe51098971ebbae1bb4292f1)
 - [a97ef07d090d24574d55b8c6f65e56ceecf8ab51](https://github.com/magento/graphql-ce/commit/a97ef07d090d24574d55b8c6f65e56ceecf8ab51)
 - [461763eb32a9fc0076bc373e8ce19b8cb25ce3bd](https://github.com/magento/graphql-ce/commit/461763eb32a9fc0076bc373e8ce19b8cb25ce3bd)

The fix will be available with the upcoming 2.3.4 release.
