### ISSUE TITLE
[Commerce] CMS page coverage 

### ISSUE THREAD

**Issue by roma-glushko** [magento/graphql-ce#106]
### Preconditions
1. Magento 2 Commerce 
2. GraphQL modules (Especially Magento_CmsGraphQl from #31)

### Description

There is need to support retrieving Commerce specific information on cmsPage GraphQL API:
- rendered content (with no Magento-specific directives) or un-rendered page content, depending on configuration 
- parent page(s)

Related ticked: #31

**Comment by naydav** [comment]
@TomashKhamlai 
Please, verify this issue
Thanks

**Comment by TomashKhamlai** [comment]
Verification:

1) In Magento Commerce, we have such thing called `hierarchy_menu' which has an impact on the layout blocks `content`, `sidebar.main`, `sidebar.additional`. Currently, I have no access to the source of expectations, that why I would like to get some examples of failing behavior. @roma-glushko could you provide it? A simple test for getting the content of widget that has "CMS Hierarchy Node Link" type showed that the widget was rendered.

@naydav, I've found that `HierarchyNodeSearchResultsInterface` could be implemented in GraphQL for Magento 2 Commerce. 

2) Banners (Dynamic Blocks) perhaps will not be rendered properly:
#### Frontend
```html
<div class="widget block block-banners" data-bind="scope: 'banner'" data-banner-id="a0fc67c4032d8ffe97ad1f0fe2b082843053d0853dc2473b5f21fe31efadc617" data-types="content,header" data-display-mode="fixed" data-ids="1" data-rotate="" data-store-id="1">
    <ul class="banner-items" data-bind="afterRender: registerBanner">
        <!-- ko foreach: getItemsa0fc67c4032d8ffe97ad1f0fe2b082843053d0853dc2473b5f21fe31efadc617() -->
        <li class="banner-item" data-bind="attr: {'data-banner-id': $data.bannerId}" data-banner-id="1">
            <div class="banner-item-content" data-bind="bindHtml: $data.html"><p><img src="http://m2-test-ee.io/pub/media/catalog/Screenshot_20190315_142632.png" alt="fdfdfds" width="600" height="300"></p>
<p><img src="http://m2-test-ee.io/pub/media/catalog/Screenshot_20190116_175605.png" alt="200" width="300" height="150"></p></div>
        </li>
        <!-- /ko -->
    </ul>
</div>
```
```graphql
<div class="widget block block-banners" data-bind="scope: 'banner'" data-banner-id="a0fc67c4032d8ffe97ad1f0fe2b082843053d0853dc2473b5f21fe31efadc617" data-types="content,header" data-display-mode="fixed" data-ids="1" data-rotate="" data-store-id="1">
    <ul class="banner-items" data-bind="afterRender: registerBanner">
        <!-- ko foreach: getItemsa0fc67c4032d8ffe97ad1f0fe2b082843053d0853dc2473b5f21fe31efadc617() -->
        <li class="banner-item" data-bind="attr: {'data-banner-id': $data.bannerId}">
            <div class="banner-item-content" data-bind="bindHtml: $data.html"></div>
        </li>
        <!-- /ko -->
    </ul>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "banner": {
                        "component": "Magento_Banner/js/view/banner"
                    }
                }
            }
        }
    }
</script>
```

It looks for me as an issue because I can't imagine how it will be rendered by third-parties without `$data`.
