### ISSUE TITLE
Implement cache tag generation for GraphQL queries

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#230]
Based on the [prototype](https://github.com/magento/graphql-ce/issues/17) and [commit](https://github.com/magento/graphql-ce/commit/0a84749bcff2e0bd2d4c42f90c26a914a0dc4b81) specifically, implement mechanism of cache tag generation for GraphQL queries. 

In scope of this task Varnish cache is not supposed to be enabled yet.

Tasks in this scope:
[x] reuse POC @cpartica 
[x] collect tags from schema and append ids to products @prabhuram93 
[x] make interface for resolver that collects ids for tags @danielrenaud 
[x] additional tags collecting from category, category in products, cms page, cms block @cpartica 
[x] exclude non cacheable queries that don't have invalidation strategy and mark the schema as non cacheable (that includes non products and non CMS so all directory & customer is not cacheable for now) 
[x] implement & reuse builtin cache  using DI plugins in graphql @cpartica 
[x] reuse varnish DI plugins in graphql area because code is seamless @cpartica 
[x] diversifying cache variation for catalog & cms & currency header, use session, ignoring cache-vary cookie (headers would invalidate cookie and they generate too many cases which don't make sense for headless) @cpartica 
[x] write tests in api functional and make sure they still work ok and caching did not affect using store & currency variations @cpartica 
[x] writing documentation @keharper

**Comment by davidverholen** [comment]
since the prototype branch does not seem to exist anymore, I'm not completely sure how this was planned or if maybe the cache tag generation was already in the poc?

(If not) I think it could be possible to do this automatically by plugging into the load methods of the resource model(s), checking for the IdentityInterface and if present, add the Identities to the response header. (edit: plugins do not work on abstract classes I think, but it would still be possible using the model_load_after event)

This should then add all cache tags of all entities that are loaded in the request.

**Comment by cpartica** [comment]
code reviews that are relevant to this ticket:
CR-MAGETWO-45403
CR-MAGETWO-45613
CR-MAGETWO-45761

Full code review excluding tests is done in github internal HB team repo CE #42
