### ISSUE TITLE
CMS page coverage

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#31]
As a Magento Developer, I want to query for CMS page content using the GraphQL API so that I can build basic ecommerce storefronts using only GraphQL  

**Use cases:** 
- Developer can query GraphQL for CMS page content and get back all necessary data to render the page on storefront or in 3rd party applications. 

**Acceptance Criteria**
- Only enabled pages will be returned by the API
- Store view context is passed in the HTTP header and only pages relevant to given context will be returned
- Staging versions of the page cannot be queried - only the currently active pages are returned
- [DRAFT] API returns the following info
   - url or url key
   - layout
   - layout update XML?
   - theme? 
   - page title
   - content heading
   - rendered (with no Magento-specific directives) or un-rendered page content, depending on configuration
   - meta title, keywords, description 
   - parent page(s)

Changes should be covered with web API functional tests. See [\Magento\GraphQl\Catalog\ProductViewTest::testQueryAllFieldsSimpleProduct](https://github.com/magento/magento2/blob/b3372064f574fd5aece0617009ee317db589febe/dev/tests/api-functional/testsuite/Magento/GraphQl/Catalog/ProductViewTest.php#L35) as an example.

**Comment by roma-glushko** [comment]
Hi @paliarush ,

I have implemented all stuff from requirements possible on Magento 2 Open Source. Some of them I had to avoid due to Commerce only features:
-  parent page(s)
- rendered (with no Magento-specific directives) or un-rendered page content, depending on configuration (PageBuilder related stuff)

This is followed up in the following ticket:  #106

Also, information under discussion is not added:
- layout update XML
- theme

PR: https://github.com/magento/graphql-ce/pull/105

Thanks!

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/166
