### ISSUE TITLE
Why both `cartItems[N].variant_sku` and `cartItems[N].data.sku` are required?

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#349]
### Steps to reproduce (*)

1. Create Configurable Product with
Name & SKU: conf
Weight: 1
Price: 1
Variations:
- sku: conf-white, qty: 12, price: 10
- sku: conf-black, qty: 12, price: 10
2. Perform GraphQL query:
```
mutation {
  addConfigurableProductsToCart(
    input: {
      cart_id: "gbK3g1pcEiyd39h2clKomLU6qsyFLAVT"
      cartItems: [
        {
          data: {
            qty: 1
            sku: "conf-black"
          }
        }
        {
          data: {
            qty: 1
            sku: "conf-white"
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        qty
        product {
          name
          sku
        }
    }
  }
  }
}
```

### Expected result (*)

1. Isn't SKU unique value?

### Actual result (*)

1. No error and only one value is required

**Comment by rogyar** [comment]
Hi
The problem is the mentioned query adds simple products to the shopping cart using endpoint for configurable products. Please note, that there's no configurable product SKU in the query. 
As result, we have two simple products in the shopping cart instead of two configurable products.
Technically, it's correct except one fact. Simple products in the shopping cart have no information about the parent (configurable) product and that's the problem. The current implementation does not allow us to provide information about configurable products in the shopping cart in the same manner as it's done within a scope of the storefront. 
We will discuss how to fix the current implementation.

**Comment by naydav** [comment]
Based on this ticket was created https://github.com/magento/graphql-ce/issues/438 with more details
