### ISSUE TITLE
Test coverage of getting IDs of CMS page/blocks by GraphQL API

### ISSUE THREAD

**Issue by galaoleksandr** [magento/graphql-ce#387]
Cover getting ID of CMS page and IDs of CMS blocks with API-functional tests.

**Comment by atwixfirster** [comment]
**PR:** https://github.com/magento/graphql-ce/pull/585

Thank you!

**Comment by naydav** [comment]
@galaoleksandr @atwixfirster 
Looks like we don't need to expand scheme with surrogate(internal/technical) keys.

`page_id` for `Page` and `block_id` for Block are surrogate keys, you should use `identifier` for loading of these entities.

The same situation with a Product where `sku` is a natural identifier but not `entity_id` (needed just for internal purposes)
That's why we don't provide a possibility to get Product by `entity_id` in GraphQL

But we still have these fields in Api
`\Magento\Cms\Api\Data\BlockInterface::BLOCK_ID`
`\Magento\Cms\Api\Data\PageInterface::PAGE_ID`

@paliarush 
Please, share you opinion
Thanks

**Comment by naydav** [comment]
https://github.com/magento/graphql-ce/pull/585
