### ISSUE TITLE
Category query returns disabled categories when including `products`

### ISSUE THREAD

**Issue by mhhansen** [magento/graphql-ce#724]
### Preconditions (*)

1. Magento 2.3.1
2. in this example, Sample Data was installed

### Steps to reproduce (*)

1. Query a specific category, ask for `name`, `id` and `products` data

`query some {
  category(id:2) {
    name
    children {
      name
      id
    }
    products {
      items {
        name
      }
    }
  }
}`

### Expected result (*)

Returns category tree only with enabled categories and product data

### Actual result (*)

1. Returns all Categories and Products
2. Includes categories that are disabled via admin panel
3. Returns disabled Category's name as "null"
 
![01 query-categories-width-products](https://user-images.githubusercontent.com/1625755/58272039-e80e5b00-7d63-11e9-8c69-9f92e56eca2b.png)

<img width="584" alt="02 admin-panel-disabled-collection-category" src="https://user-images.githubusercontent.com/1625755/58272060-f8263a80-7d63-11e9-8c7f-f976f0414691.png">

![01 admin-panel-disabled-promotions-category](https://user-images.githubusercontent.com/1625755/58272096-155b0900-7d64-11e9-928e-e113f31d7550.png)

If you don't ask for `products`, query works OK
![03 query-categories-without-products-works-OK](https://user-images.githubusercontent.com/1625755/58272015-d88f1200-7d63-11e9-9a54-e7a664179af6.png)

**Comment by TomashKhamlai** [comment]
For reference #139 #463
Reproduced

**Comment by TomashKhamlai** [comment]
@naydav, please set the complexity of the task and milestone.

**Comment by mhhansen** [comment]
I think depth in `lteq` is being miscalculated, returning `AND e.level <= 3` when `products` set is added. Without `products`, it returns `AND e.level <= 2` and works OK.
```
# Magento\CatalogGraphQl\Model\Resolver\Products\DataProvider\CategoryTree::getTree()

$collection->addFieldToFilter('level', ['lteq' => $level + $depth - self::DEPTH_OFFSET]);
```
<img width="861" alt="01 query-with-products" src="https://user-images.githubusercontent.com/1625755/58433958-be20a580-808f-11e9-90e5-def435cd6672.png">

<img width="957" alt="02 query-without-products" src="https://user-images.githubusercontent.com/1625755/58433975-cb3d9480-808f-11e9-83c5-a747f2536142.png">


As far as I saw in `DepthCalculator::calculate()`, `products` node is `Field` kind and not considered as `InlineFragment` (not sure if it should), but a quick/dirty(?) check to avoid it's calculation, makes the query to work OK
```
# Magento\CatalogGraphQl\Model\Category\DepthCalculator::calculate()
# adding the `OR` evaluation
if ($node->kind === 'InlineFragment' || $node->name->value === 'products') {
    continue;
}
```
<img width="833" alt="03 with-dirty-check-in-depth" src="https://user-images.githubusercontent.com/1625755/58433409-929cbb80-808d-11e9-9d7b-29a5465c04ea.png">

Not sure if the path that I took is useful, but wanted to provide more context on this.

**Comment by barbanet** [comment]
Hi!

@mhhansen and I were talking about this issue and I tested with an updated (a few minutes ago) form from Github (I'm not using Composer install for Magento).
I made a simple test and I found this:

I have 2 categories with the same products on both categories.
The second category is not enable.

![2019-05-27-02](https://user-images.githubusercontent.com/392385/58435728-4f941580-8098-11e9-9296-2655dd34a7b4.png)

If if run the query I get:

![2019-05-27-03](https://user-images.githubusercontent.com/392385/58435748-6470a900-8098-11e9-900e-a22015bb758a.png)

Is ok to think that probably this issue was solved on 2.3-develop branch ?

**Comment by avattam06** [comment]
When 2 categories are created with some products on both categories.
and the second category is disabled. The Query shows only enabled categories, which is the expected behaviour on 2.3-develop. The above issue which "Returns disabled Category's name as null" occurs when there are subcategories in the disabled category and they are set to active.![Screen Shot 2019-07-09 at 9.25.55 AM.png](https://images.zenhubusercontent.com/5bd345048fc9d2096be14457/3a340b2c-f99a-48ad-8d8e-6189c4705c7b)![Screen Shot 2019-07-09 at 9.26.07 AM.png](https://images.zenhubusercontent.com/5bd345048fc9d2096be14457/8d359eb5-223c-452d-aeb3-541df8f362f1)![Screen Shot 2019-07-09 at 9.26.22 AM.png](https://images.zenhubusercontent.com/5bd345048fc9d2096be14457/ee17d5cd-1453-40a2-a9a1-eb9aee529795)![Screen Shot 2019-07-09 at 9.26.48 AM.png](https://images.zenhubusercontent.com/5bd345048fc9d2096be14457/1732deae-5699-4708-a3f9-71a64ced8fc8)![Screen Shot 2019-07-09 at 9.27.16 AM.png](https://images.zenhubusercontent.com/5bd345048fc9d2096be14457/e443e310-7c2f-411f-9997-af3fe37be718)

**Comment by naydav** [comment]
Hello @mhhansen,
Agree with the previous comment.

Disabled categories should be absent in a result (no name, no id, no null... just absent)... for a client, it should be like a category does not exist.

@TomashKhamlai Could you verify this issue?
Thanks

**Comment by TomashKhamlai** [comment]
I also agree. I can confirm that
> "Returns disabled Category's name as null" occurs when there are subcategories in the disabled category and they are set to active
is a good description of the problem

**Comment by TomashKhamlai** [comment]
When disabled category contains active categories and user acquires data about some category that is some parent up in the tree (not necessarily direct parent) then for any disabled category property `name` is returned as null.

To reproduce this issue you need just working instance with sample data and one request where you acquire information for category with id 2 (Default category)

**Comment by TomashKhamlai** [comment]
Issue remains the same.

**Comment by naydav** [comment]
Related internal ticket MC-17988
