### ISSUE TITLE
Partial Automation of GraphQL Docs

### ISSUE THREAD

**Issue by misha-kotov** [magento/graphql-ce#76]
As a Magento core developer, I'd like the GraphQL objects to be well documented automatically so that their intention can be well understood and we spend minimal time on describing objects whose docs can be automatically generated. 

**Examples:** 
- When a return object is an array of sub-objects, we can automatically generate a blob like "Returns an array of <sub-objects>. A <sub-object> is <definition>"
- Others? 

This is still in ideation phase. Need to brainstorm further examples to create appropriate Acceptance Criteria. 

**Acceptance Criteria:**
1. While development mode is enabled the documentation should include the Handler that was used to resolve the query: `ReachDigital\GraphQLInventory\Handler::execute`

**Comment by paales** [comment]
The introspection query by default already exposes the inheritance of GraphQL objects, so that might not be required to implement in the document section as well.

While development mode is enabled the documentation should include the Handler that was used to resolve the query: `ReachDigital\GraphQLInventory\Handler::execute`
