### ISSUE TITLE
[Checkout] Replace usage of CartItemQuantity with CartItemInterface

### ISSUE THREAD

**Issue by paliarush** [magento/graphql-ce#890]
Acceptance criteria:
1. `ShippingCartAddress` has field `cart_items`, which should return `CartItemInterface` instead of `CartItemQuantity`
2. All fields in `CartItemQuantity` should be deprecated (so this type can be completely removed in the future releases)
3. Since `CartItemInterface` is wider than `CartItemQuantity`, custom resolver may need to be implemented for the missing fields
4. Deprecate `items_weight` in `ShippingCartAddress`
4. Changes must be covered with API functional tests

**Comment by lenaorobei** [comment]
As per discussion with @paliarush and @buskamuza it was decided to introduce `cart_items_v2` to keep backward compatibility.

**Comment by magento-engcom-team** [comment]
Hi @paliarush. Thank you for your report. 
The issue has been fixed in magento/graphql-ce#899 by @VitaliyBoyko in 2.3-develop branch
Related commit(s):
 - [b3f510d037dffb62b70fb14d7f3fba63b9670a43](https://github.com/magento/graphql-ce/commit/b3f510d037dffb62b70fb14d7f3fba63b9670a43)
 - [f7ab08e6103ad1a1b503b6226e9edad53f6e7700](https://github.com/magento/graphql-ce/commit/f7ab08e6103ad1a1b503b6226e9edad53f6e7700)
 - [94e8f148bdbbff36cb28faea9f967816f7d8b8e4](https://github.com/magento/graphql-ce/commit/94e8f148bdbbff36cb28faea9f967816f7d8b8e4)
 - [77e3a9cc2087bf9396649e7b8896bef13a2c9680](https://github.com/magento/graphql-ce/commit/77e3a9cc2087bf9396649e7b8896bef13a2c9680)
 - [863d178be4baf88fffc7b252c0a92f6edb0410e5](https://github.com/magento/graphql-ce/commit/863d178be4baf88fffc7b252c0a92f6edb0410e5)
 - [62971990536fea8aadb9eb91f407c4b7eda61d10](https://github.com/magento/graphql-ce/commit/62971990536fea8aadb9eb91f407c4b7eda61d10)
 - [795931f1bb0ca75389a974710d4dfff37561af00](https://github.com/magento/graphql-ce/commit/795931f1bb0ca75389a974710d4dfff37561af00)
 - [c9c13a6c123507462ee5b18b50ce74b3c40076e0](https://github.com/magento/graphql-ce/commit/c9c13a6c123507462ee5b18b50ce74b3c40076e0)
 - [8b51315687fe2891ed731ef821c0719a6d995765](https://github.com/magento/graphql-ce/commit/8b51315687fe2891ed731ef821c0719a6d995765)
 - [344648f002ecbd5ced22680e445ce4dfa82d3637](https://github.com/magento/graphql-ce/commit/344648f002ecbd5ced22680e445ce4dfa82d3637)
 - [b9f708bc25f4cb389bdb3e109e01a543d4179a85](https://github.com/magento/graphql-ce/commit/b9f708bc25f4cb389bdb3e109e01a543d4179a85)

The fix will be available with the upcoming 2.3.4 release.
